import { TeamMember } from "./team-types";

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "mock-investor-1",
    name: "Д.Энхтөр",
    role: "Хөрөнгө оруулагч",
    department: "Хөрөнгө оруулагчид",
    bio: "Платформын өсөлт, санхүүжилтийн стратеги, бизнесийн өргөжилтийн чиглэлд зөвлөмж өгдөг.",
    avatarUrl: null,
    email: "investor@mglstore.mn",
    linkedinUrl: null,
    experience: "10 жил",
    skills: ["Investor", "Growth", "Finance"],
    order: 0,
  },
  {
    id: "mock-advisor-1",
    name: "Ц.Ариунболд",
    role: "Стратегийн зөвлөх",
    department: "Зөвлөхүүд",
    bio: "Байгууллагын хөгжил, үйл ажиллагааны загвар, урт хугацааны түншлэлийн бодлогод зөвлөхөөр оролцдог.",
    avatarUrl: null,
    email: "advisor@mglstore.mn",
    linkedinUrl: null,
    experience: "12 жил",
    skills: ["Advisor", "Operations", "Partnership"],
    order: 0,
  },
  {
    id: "mock-team-1",
    name: "Г.Тэмүүжин",
    role: "HR",
    department: "Захиргаа удирдлагын хэлтэс",
    bio: "Байгууллагын хүний нөөцийн бодлого, ажилтны туршлага, дотоод соёлыг тасралтгүй сайжруулах ажлыг хариуцан ажилладаг.",
    avatarUrl: null,
    email: "temuujin@mglstore.mn",
    linkedinUrl: null,
    experience: "2 жил",
    skills: ["HR", "Сонгон шалгаруулалт", "Дотоод соёл"],
    order: 1,
  },
  {
    id: "mock-team-2",
    name: "Ж.Намуун",
    role: "HR",
    department: "Захиргаа удирдлагын хэлтэс",
    bio: "Ажилтны бүртгэл, сургалт хөгжил, багийн өдөр тутмын зохион байгуулалтад төвлөрөн ажилладаг.",
    avatarUrl: null,
    email: "namuun@mglstore.mn",
    linkedinUrl: null,
    experience: "2 жил",
    skills: ["Сургалт", "Төлөвлөлт", "Харилцаа"],
    order: 2,
  },
  {
    id: "mock-team-4",
    name: "Э.Бат-Эрдэнэ",
    role: "Бүтээгдэхүүн хөгжүүлэлтийн менежер",
    department: "Бүтээгдэхүүн хөгжүүлэлтийн хэлтэс",
    bio: "MGL Store-ийн хэрэглэгчийн урсгал, үйлчилгээний бүтэц, шинэ боломжуудын судалгаа хөгжүүлэлтийг ахалдаг.",
    avatarUrl: null,
    email: "bat-erdene@mglstore.mn",
    linkedinUrl: null,
    experience: "4 жил",
    skills: ["Product", "UX research", "Strategy"],
    order: 4,
  },
  {
    id: "mock-team-5",
    name: "А.Мөнхзул",
    role: "UI/UX дизайнер",
    department: "Бүтээгдэхүүн хөгжүүлэлтийн хэлтэс",
    bio: "Веб болон мобайл интерфэйсийн хэрэглэгчийн туршлага, visual system, component consistency дээр ажилладаг.",
    avatarUrl: null,
    email: "munkhzul@mglstore.mn",
    linkedinUrl: null,
    experience: "3 жил",
    skills: ["UI design", "UX", "Design system"],
    order: 5,
  },
  {
    id: "mock-team-6",
    name: "Д.Анхбаяр",
    role: "Frontend хөгжүүлэгч",
    department: "Технологийн хэлтэс",
    bio: "Marketplace, checkout, байгууллагын профайл зэрэг хэрэглэгчийн талын интерфэйсүүдийг хөгжүүлж, performance болон accessibility дээр анхаардаг.",
    avatarUrl: null,
    email: "ankhbayar@mglstore.mn",
    linkedinUrl: null,
    experience: "5 жил",
    skills: ["Next.js", "React", "Tailwind"],
    order: 6,
  },
  {
    id: "mock-team-7",
    name: "С.Билгүүн",
    role: "Backend хөгжүүлэгч",
    department: "Технологийн хэлтэс",
    bio: "API, өгөгдлийн сан, төлбөрийн интеграц, байгууллагын системүүдийн найдвартай ажиллагааг хариуцдаг.",
    avatarUrl: null,
    email: "bilguun@mglstore.mn",
    linkedinUrl: null,
    experience: "5 жил",
    skills: ["Node.js", "Prisma", "PostgreSQL"],
    order: 7,
  },
  {
    id: "mock-team-8",
    name: "О.Номин",
    role: "Маркетингийн менежер",
    department: "Маркетинг борлуулалтын хэлтэс",
    bio: "Сошиал контент, кампанит ажил, брэндийн мессеж, хэрэглэгчийн идэвхжүүлэлтийн төлөвлөгөөг гарган хэрэгжүүлдэг.",
    avatarUrl: null,
    email: "nomin@mglstore.mn",
    linkedinUrl: null,
    experience: "4 жил",
    skills: ["Marketing", "Content", "Campaign"],
    order: 8,
  },
  {
    id: "mock-team-9",
    name: "П.Энхжин",
    role: "Борлуулалтын зөвлөх",
    department: "Маркетинг борлуулалтын хэлтэс",
    bio: "Түнш байгууллагуудтай харилцах, санал болгох үйлчилгээний багц, гэрээний эхний шатны зөвлөгөөг хариуцдаг.",
    avatarUrl: null,
    email: "enkhjin@mglstore.mn",
    linkedinUrl: null,
    experience: "3 жил",
    skills: ["Sales", "Partnership", "CRM"],
    order: 9,
  },
  {
    id: "mock-team-10",
    name: "М.Төгөлдөр",
    role: "Логистик зохицуулагч",
    department: "Үйл ажиллагааны хэлтэс",
    bio: "Захиалга, хүргэлт, агуулахын уялдаа холбоог сайжруулж, өдөр тутмын үйл ажиллагааны тасралтгүй байдлыг хангадаг.",
    avatarUrl: null,
    email: "tuguldur@mglstore.mn",
    linkedinUrl: null,
    experience: "4 жил",
    skills: ["Operations", "Logistics", "Coordination"],
    order: 10,
  },
  {
    id: "mock-team-11",
    name: "Л.Саруул",
    role: "Санхүүгийн мэргэжилтэн",
    department: "Санхүүгийн хэлтэс",
    bio: "Төлбөр тооцоо, тайлан, гэрээний санхүүгийн мэдээлэл болон байгууллагын дотоод хяналтад төвлөрөн ажилладаг.",
    avatarUrl: null,
    email: "saruul@mglstore.mn",
    linkedinUrl: null,
    experience: "6 жил",
    skills: ["Finance", "Reporting", "Control"],
    order: 11,
  },
];
