services:
  - type: web
    name: mgl-web
    rootDir: .
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm -F @mgl/database run db:generate && pnpm build && cd apps/web && pnpm build
    startCommand: cd apps/web && pnpm exec next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false

  - type: web
    name: mgl-admin
    rootDir: .
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm -F @mgl/database run db:generate && pnpm build && cd apps/admin && pnpm build
    startCommand: cd apps/admin && pnpm exec next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: mgl-vendor
    rootDir: .
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm -F @mgl/database run db:generate && pnpm build && cd apps/vendor && pnpm build
    startCommand: cd apps/vendor && pnpm exec next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: mgl-api
    rootDir: .
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm exec prisma migrate deploy --schema=packages/database/prisma/schema.prisma && pnpm -F @mgl/database run db:generate && pnpm build && cd apps/api && pnpm build
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false

databases:
  - name: mglstore
    databaseName: mglstore
    user: mglstore
    plan: standard
    version: "15"
