export enum ReturnStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum InventoryReason {
  ORDER = "ORDER",
  RETURN = "RETURN",
  RESTOCK = "RESTOCK",
  MANUAL_ADJUST = "MANUAL_ADJUST",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum OnboardingSource {
  ADMIN = "ADMIN",
  SELF_SERVICE = "SELF_SERVICE",
}

export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  ORDER_CREATED = "ORDER_CREATED",
  ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED",
  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_STATUS_CHANGED = "PAYMENT_STATUS_CHANGED",
  DELIVERY_STATUS_CHANGED = "DELIVERY_STATUS_CHANGED",
  RETURN_STATUS_CHANGED = "RETURN_STATUS_CHANGED",

  REGISTRATION_REQUEST_CREATED = "REGISTRATION_REQUEST_CREATED",
  REGISTRATION_REQUEST_APPROVED = "REGISTRATION_REQUEST_APPROVED",
  REGISTRATION_REQUEST_REJECTED = "REGISTRATION_REQUEST_REJECTED",
  USER_CREATED_BY_ADMIN = "USER_CREATED_BY_ADMIN",

  PRODUCT_REQUEST_CREATED = "PRODUCT_REQUEST_CREATED",
  PRODUCT_REQUEST_APPROVED = "PRODUCT_REQUEST_APPROVED",
  PRODUCT_REQUEST_REJECTED = "PRODUCT_REQUEST_REJECTED",
  PRODUCT_REQUEST_CHANGES_REQUESTED = "PRODUCT_REQUEST_CHANGES_REQUESTED",
  PRODUCT_PUBLISHED = "PRODUCT_PUBLISHED",
}
