export enum PlatformRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  HR_ADMIN = "HR_ADMIN",
  CONTENT_ADMIN = "CONTENT_ADMIN",
  PARTNER_ADMIN = "PARTNER_ADMIN",
  WAREHOUSE_ADMIN = "WAREHOUSE_ADMIN",
  FINANCE_ADMIN = "FINANCE_ADMIN",
  SERVICE_ADMIN = "SERVICE_ADMIN",
  LAWYER = "LAWYER",
  USER = "USER",
}

export enum OrgRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  STAFF = "STAFF",
  VIEWER = "VIEWER",
}

export enum Capability {
  POS_CASHIER = "POS_CASHIER",
  DELIVERY_DRIVER = "DELIVERY_DRIVER",
  STOCK_MANAGER = "STOCK_MANAGER",
  ORDER_PROCESSOR = "ORDER_PROCESSOR",
  SALES_REPRESENTATIVE = "SALES_REPRESENTATIVE",
}

export enum Permission {
  // Platform-level
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_ORGANIZATIONS = "MANAGE_ORGANIZATIONS",
  MANAGE_REGISTRATIONS = "MANAGE_REGISTRATIONS",
  VIEW_SYSTEM_DASHBOARD = "VIEW_SYSTEM_DASHBOARD",
  MANAGE_CATEGORIES = "MANAGE_CATEGORIES",
  MANAGE_SITE_SETTINGS = "MANAGE_SITE_SETTINGS",
  MANAGE_SITE_CONTENT = "MANAGE_SITE_CONTENT",
  MANAGE_JOB_POSITIONS = "MANAGE_JOB_POSITIONS",
  MANAGE_JOB_APPLICATIONS = "MANAGE_JOB_APPLICATIONS",
  MANAGE_INVESTORS = "MANAGE_INVESTORS",
  MANAGE_FORMS = "MANAGE_FORMS",
  MANAGE_ADMIN_STAFF = "MANAGE_ADMIN_STAFF",
  // Organization-level
  MANAGE_ORG_SETTINGS = "MANAGE_ORG_SETTINGS",
  MANAGE_ORG_MEMBERS = "MANAGE_ORG_MEMBERS",
  MANAGE_PRODUCTS = "MANAGE_PRODUCTS",
  APPROVE_PRODUCTS = "APPROVE_PRODUCTS",
  MANAGE_ORDERS = "MANAGE_ORDERS",
  VIEW_ORDERS = "VIEW_ORDERS",
  MANAGE_POS = "MANAGE_POS",
  OPERATE_POS = "OPERATE_POS",
  MANAGE_STOCK = "MANAGE_STOCK",
  REQUEST_STOCK = "REQUEST_STOCK",
  MANAGE_DELIVERIES = "MANAGE_DELIVERIES",
  MAKE_DELIVERIES = "MAKE_DELIVERIES",
  VIEW_ORG_DASHBOARD = "VIEW_ORG_DASHBOARD",
  MANAGE_SERVICES = "MANAGE_SERVICES",
  MANAGE_WAREHOUSES = "MANAGE_WAREHOUSES",
  MANAGE_CHAT = "MANAGE_CHAT",
}
