-- Add new PlatformRole enum values
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'HR_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'CONTENT_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'PARTNER_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'WAREHOUSE_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'FINANCE_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'SERVICE_ADMIN';
