ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "taxType" TEXT NOT NULL DEFAULT 'VAT_ABLE',
  ADD COLUMN IF NOT EXISTS "cityTaxRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "classificationCode" TEXT NOT NULL DEFAULT '4711000',
  ADD COLUMN IF NOT EXISTS "taxProductCode" TEXT;

ALTER TABLE "PosSaleLine"
  ADD COLUMN IF NOT EXISTS "productBarcode" TEXT,
  ADD COLUMN IF NOT EXISTS "taxType" TEXT NOT NULL DEFAULT 'VAT_ABLE',
  ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "cityTaxRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cityTaxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "classificationCode" TEXT NOT NULL DEFAULT '4711000',
  ADD COLUMN IF NOT EXISTS "taxProductCode" TEXT,
  ADD COLUMN IF NOT EXISTS "measureUnit" TEXT NOT NULL DEFAULT 'pcs';
