ALTER TABLE "Contract"
  ADD COLUMN IF NOT EXISTS "systemQrInvoiceId" TEXT,
  ADD COLUMN IF NOT EXISTS "paymentSystem" TEXT DEFAULT 'QPAY';

ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
